source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '12.0'

target 'IronSourceSwiftDemoApp' do
  # Comment the next line if you don't want to use dynamic frameworks
 use_frameworks!

    pod 'IronSourceSDK' 
  # Pods for IronSourceSwiftDemoApp

end
