package com.ironsource.ironsourcesdkdemo

enum class DemoButtonIdentifiers {
    LOAD_REWARDED_AD_BUTTON_IDENTIFIER,
    SHOW_REWARDED_AD_BUTTON_IDENTIFIER,
    LOAD_INTERSTITIAL_AD_BUTTON_IDENTIFIER,
    SHOW_INTERSTITIAL_AD_BUTTON_IDENTIFIER,
    LOAD_BANNER_AD_BUTTON_IDENTIFIER,
    DESTROY_BANNER_BUTTON_IDENTIFIER
}

